[WIP] azure flow logs from storage accounts
illumio/terraform-illumio-cloudsecure pull request #21
Opened 2024-10-29 22:21 UTC by shireesh-illumio

2024-10-30 23:21 UTC, rlenglet requested changes
Looks good overall.
I just have a few relatively minor comments.

2024-10-30 23:21 UTC, rlenglet commented on modules/azure_flow_logs_storage_accounts/variables.tf
> +  type    = list(object({
Can't this be a `set`?

2024-10-30 23:21 UTC, rlenglet commented on examples/azure_flow_logs_storage_accounts/versions.tf
> +      version = ">= 1.1.0"
The `azure_flow_logs_storage_account` resource got added in 1.2.0.
```suggestion
      version = ">= 1.2.0"
```

2024-10-30 23:21 UTC, rlenglet commented on examples/azure_flow_logs_storage_accounts/main.tf
> +      name               = "bucket_name"
```suggestion
      name                = "bucket_name"
```

2024-10-30 23:21 UTC, rlenglet commented on examples/azure_flow_logs_storage_accounts/main.tf
> +}
Add `tags`.

2024-10-30 23:21 UTC, rlenglet commented on examples/azure_flow_logs_storage_accounts/main.tf
> +  source = "illumio/cloudsecure/illumio//modules/azure_flow_logs_storage_account"
```suggestion
  source = "illumio/cloudsecure/illumio//modules/azure_flow_logs_storage_accounts"
```

2024-10-30 23:21 UTC, rlenglet commented on examples/azure_flow_logs_storage_accounts/main.tf
> +module "azure_flow_logs_storage_account_dev" {
```suggestion
module "azure_flow_logs_storage_accounts" {
```

2024-11-06 18:57 UTC, shireesh-illumio commented on modules/azure_flow_logs_storage_accounts/variables.tf
none of the resource in the module can accommodate tags. 
the one you pointed out was a data resource.

2024-11-06 18:57 UTC, shireesh-illumio commented on modules/azure_flow_logs_storage_accounts/variables.tf
> +  description = "The list of storage accounts to be monitored."
we are using data source to fetch the accounts which might be having flow logs.

2024-11-06 18:57 UTC, shireesh-illumio commented on modules/azure_subscription/outputs.tf
> +output "azure_secret_expiration_days" {
thank you

2024-11-06 18:57 UTC, shireesh-illumio commented on modules/azure_subscription/outputs.tf
> +output "service_principal_id" {
thank you

2024-11-06 18:57 UTC, shireesh-illumio commented on modules/azure_subscription/outputs.tf
users when using the module can use these default applied values to test their code with whats created on aws. Agree it needs to be at all places. will do so in another pr.

2024-11-06 18:57 UTC, shireesh-illumio commented on modules/azure_flow_logs_storage_accounts/main.tf
> +  storage_accounts_map = {
changed to set in variable itself. not needed anymore.

2024-11-06 18:57 UTC, shireesh-illumio commented on modules/azure_flow_logs_storage_accounts/main.tf
> +data "azurerm_storage_account" "account" {
this is a data resource.

2024-11-06 18:57 UTC, shireesh-illumio commented on modules/azure_flow_logs_storage_accounts/main.tf
> +  name                = each.value.name
data resource.

2024-11-14 00:38 UTC, rlenglet requested changes
Looks great! I only have a few minor comments.

2024-11-14 00:38 UTC, rlenglet commented on modules/azure_subscription/outputs.tf
> +  value       = var.azure_secret_expiration_days
At least use the same name for consistency.
```suggestion
output "azure_secret_expiration_days" {
  value       = var.azure_secret_expiration_days
```

2024-11-14 00:38 UTC, rlenglet commented on modules/azure_subscription/outputs.tf
> +}
This is meant to be used as input for `azure_flow_logs_storage_accounts`'s `service_principal_client_id` variable. Use the same name to make that obvious.
```suggestion
output "service_principal_client_id" {
  value       = azuread_service_principal.illumio_sp.object_id
  description = "The ID of the service principal created for Illumio CloudSecure."
}
```

2024-11-14 00:38 UTC, rlenglet commented on examples/azure_flow_logs_storage_accounts/main.tf
> +  service_principal_client_id = module.azure_subscription_dev.service_principal_id
Fix here after renaming.
```suggestion
  service_principal_client_id = module.azure_subscription_dev.service_principal_client_id
```

2024-11-14 00:38 UTC, rlenglet commented on modules/azure_flow_logs_storage_accounts/variables.tf
> +  description = "The client ID of the service principal used to access the storage accounts."
Clarify a bit.
```suggestion
  description = "The client ID of the service principal used by CloudSecure to access the storage accounts."
```

2024-11-14 00:38 UTC, rlenglet commented on modules/azure_flow_logs_storage_accounts/variables.tf
> +  description = "The set of storage accounts to retrieve information for."
Reword to be consistent with `aws_flow_logs_s3_buckets`:
/variables.tf
```suggestion
  description = "The set of storage accounts containing flow logs."
```

2024-11-14 00:38 UTC, rlenglet commented on modules/azure_flow_logs_storage_accounts/main.tf
> +
Remove this extra empty line.
```suggestion
```

2024-11-14 00:46 UTC, rlenglet submitted a review, later dismissed
LGTM!!

2024-11-14 00:47 UTC, rlenglet approved these changes

2024-11-14 01:19 UTC, rlenglet approved these changes

2024-11-14 01:20 UTC, merged